---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Copy nginx cfg
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_available_dir }}"

- name: Validate nginx cfg
  command: nginx -t
  register: nginx_validation
  failed_when: nginx_validation.rc != 0
  changed_when: false

- name: Enable nginx
  file:
    src: "{{ nginx_available_dir }}"
    dest: "{{ nginx_enabled_dir }}"
    state: link

- name: Check nginx state
  service:
    name: nginx
    state: started
    enabled: true
  notify: Reload nginx
